<?php require_once('header.php'); ?>

<article>
    <header>
        <h1>Entretien avec Simon Rogers, le monsieur data du Guardian</h1>
    </header>
    <div class="body">
        <p>Simon Rogers édite le Data Blog du Guardian et a participé pour son journal à l'exploitation des fuites de Wikileaks. Interview par l'atelier des Médias d'un des principaux datajournalistes.</p>
        <p>
            Il y a quelques jours,
            L’Atelier des Médias de RFI a profité du passage par Paris de
            <a href="http://www.guardian.co.uk/profile/simonrogers">Simon Rogers</a>,
            “Monsieur data” au
            <a href="http://www.guardian.co.uk/">Guardian</a>
            pour l’interroger sur son parcours et sur cette nouvelle tendance du journalisme :
            le data-journalisme ou journalisme de données.
            Simon Rogers édite le <a href="http://www.guardian.co.uk/news/datablog">Data Blog du Guardian</a>.
            Il a participé pour son journal à l’exploitation des fuites de Wikileaks sur l’Afghanistan et sur l’Irak.
            Malgré sa modestie et la simplicité avec laquelle il expose ses points de vue,
            c’est certainement une des principales personnalités
            et un des principaux moteurs du data-journalisme et de la visualisation de données dans le monde.
            Ci-dessous, une retranscription aussi fidèle que possible de cet entretien
            que vous pouvez également télécharger
            (<a href="http://telechargement.rfi.fr.edgesuite.net/rfi/francais/audio/modules/actu/R131/ADM154-1_Simon-ROGERS-VF.mp3">VF</a>
            ou <a href="http://telechargement.rfi.fr.edgesuite.net/rfi/francais/audio/modules/actu/R131/ADM154-1_Simon-ROGERS.mp3">VO</a>).
        </p>

        <h2>Atelier des Médias (ADM) : Pour commencer, est-ce que vous pouvez nous présenter votre blog et nous parler de votre parcours?</h2>

        <p>Ce  que nous faisons c’est publier des ensembles de données brutes. On les  met à disposition du monde et on demande à notre public de s’en servir,  d’en faire quelque chose. Parallèlement, on dirige un service au sein du  Guardian qui analyse et rend exploitable des données par nos  journalistes, c’est ce qu’on appelle en fait du data-journalisme, du  journalisme de données : transformer une masse de données en  information, en histoire qu’on peut raconter à nos lecteurs. J’ai  commencé à travailler au <a href="http://www.guardian.co.uk/world/september11">Guardian le 10 septembre 2001</a>,  c’était mon premier jour ! Le lendemain, j’ai vu le monde devenir  complètement fou. Il se passait tellement de choses en même temps qu’on a  eu besoin de <a href="http://www.guardian.co.uk/flash/0,,567616,00.html">produire des infographies pour les expliquer</a>.  Il y avait trop d’infos, de données, à gérer pour confier cela  uniquement à des graphistes. Je me suis donc retrouvé à bosser sur des  graphiques avec des designers pour expliquer l’information avec des  visuels. C’est comme cela que j’ai commencé à collecter des masses de  données.</p>
        <p>Par la suite, en mars 2009, le Guardian a lancé sa <a href="http://www.guardian.co.uk/open-platform">plateforme ouverte (open platform)</a> destinées aux développeurs et aux technophiles. Elle leur permet <a href="http://explorer.content.guardianapis.com/#/?format=json&amp;order-by=newest">d’interroger les données</a> du Guardian et de réaliser <a href="http://www.guardian.co.uk/open-platform/apps">des applications</a> à partir de ces données. Par exemple, on peut fabriquer une application  qui permet, quand on est dehors, d’entrer notre adresse et  l’application nous dit quels sont les restaurants alentours avec les  critiques du Guardian. C’est cela l’idée de la plateforme ouverte. Au  moment où le journal a proposé ce service d’accès à ses données, on a  pensé que ce serait bien <a href="http://www.guardian.co.uk/news/datablog/2009/mar/10/blogpost1">d’ouvrir parallèlement un data blog</a>,  un blog de données. On a publié quelques paquets de données pensant que  cela intéresserait un petit nombre de développeurs. En fait cela a vite  décollé, c’est devenu un blog qui reçoit deux fois plus de visites que  le <a href="http://www.statistics.gov.uk/hub/index.html">département officiel des statistiques du Royaume Uni</a>. Beaucoup de gens visitent notre site parce qu’ils cherchent des informations brutes sur, par exemple, <a href="http://www.guardian.co.uk/environment/datablog/2009/dec/07/copenhagen-climate-change-summit-carbon-emissions-data-country-world">les émissions de carbone dans l’ensemble du pays</a> ou <a href="http://www.guardian.co.uk/news/datablog/2010/aug/09/pakistan-flood-aid">quelles aides a reçu le Pakistan</a> en provenance de quel pays après les inondations. En fait, tout peut  être envisagé comme des données.</p>
        <p>On a par exemple publié tous <a href="http://www.guardian.co.uk/music/datablog/2009/sep/10/beatles-lyrics-words-music-rock-band">les mots utilisés par les Beatles dans leurs chansons</a>.  Combien de fois ont-ils employé le mot « love » (amour) ? 613 fois  figurez-vous. Tout peut être transformé en données. Et ce qu’il y a de  magique, c’est qu’une fois que vous avez transformé quelque chose en  chiffres et en tableaux, les gens peuvent s’en servir pour faire des  visualisations, des graphiques et des analyses.</p>

        <figure>
            <img src="http://owni.fr/files/2010/11/640x450xglobal-emissions-since-kyoto.jpg.pagespeed.ic.tt6v6VR7cy.jpg" />
        </figure>

        <h2>ADM : Quand on vous écoute, on a  l’impression que c’est presque par chance ou par hasard que vous avez  développé le journalisme de données dans votre journal, alors que c’est  un phénomène qu’on voit prendre de l’ampleur dans beaucoup de médias.  Comment cela s’est passé concrètement ?</h2>
        <p>En fait quand on a mis en ligne <a href="http://www.guardian.co.uk/news/datablog/2009/mar/10/blogpost1">le data blog en mars 2009</a>, c’était une thématique encore très confidentielle. Après cela, le gouvernement américain a lancé <a href="http://www.data.gov/">data.gov</a>,  et puis cela s’est étendu au monde entier. Depuis un an, de plus en  plus de gouvernements publient leurs données. Ils ont maintenant une  vraie pression qui les incite à rendre leurs données publiques dans des  formats exploitables par tous. Plutôt que d’utiliser du .pdf, qui est le  format traditionnellement utilisé par les gouvernements, on leur  demande <a href="http://www.kable.co.uk/councils-csv-spending-data-13sept10">des formats exploitables</a> comme le .csv ou .xls. En résumé, on a eu de la chance et puis il faut  avouer qu’il y avait une tendance quand même. Les gens veulent de  l’information brute.</p>
        <p>Mon grand-père veut savoir <a href="http://www.guardian.co.uk/environment/datablog/2010/jan/22/us-corn-production-biofuel-ethanol">le prix du pétrole</a>,  où puis-je trouver cette information ? Et comment savoir si ce sont des  données fiables ? Par exemple au Royaume Uni, le PIB est une donnée  très importante, c’est publié tous les mois. <a href="http://www.statistics.gov.uk/hub/search/index.html?newquery=GDP">Si vous allez voir sur le site des statistiques officielles</a>,  vous allez trouver 9 ou 10 manières différentes de calculer le PIB.  Comment savoir quelle est la bonne méthode ? Ça c’est une question qu’on  s’est déjà posée au Guardian <a href="http://www.guardian.co.uk/news/datablog/2009/nov/25/gdp-uk-1948-growth-economy">à laquelle on a déjà trouvé des réponses</a> parce qu’on en a besoin, donc on partage notre savoir faire.</p>

        <h2>ADM : Comment vous voyez la relation  du journalisme de données avec le journalisme en général ? Est-ce que  cela doit être une partie du journalisme ou est-ce que cela doit être un  peu partout ?</h2>
        <p>De mon point de vue, chaque sujet comporte une dimension « données »  en lui. D’un point de vue technique, ce n’est pas si compliqué, ce doit  être un outil de plus pour les journalistes. On ne doit pas envisager  cela comme un machin insurmontable et flippant. C’est juste une autre  manière d’accéder à l’information. En réalité, la plupart des choses que  l’on fait sont très simples. On utilise des logiciels que tout le monde  possède. On a tous un tableur sur notre ordinateur, <a href="http://www.google.fr/url?sa=t&amp;source=web&amp;cd=5&amp;ved=0CE4QFjAE&amp;url=http%3A%2F%2Ffr.wikipedia.org%2Fwiki%2FMicrosoft_Excel&amp;rct=j&amp;q=excel&amp;ei=7A7cTJfIFI-7hAe_kcDcAg&amp;usg=AFQjCNHn0axWvDAV1nBgu8K2NX-FfHW1cQ&amp;sig2=TX3SLSRC5GWGOD_DhtwTxA&amp;cad=rja">Excel</a>, <a href="http://www.google.fr/url?sa=t&amp;source=web&amp;cd=1&amp;sqi=2&amp;ved=0CCEQFjAA&amp;url=http%3A%2F%2Ffr.openoffice.org%2F&amp;rct=j&amp;q=openoffice&amp;ei=Bw_cTKKcCMqXOsi69N4I&amp;usg=AFQjCNFAawFHYGJRKnng1RSnc4thT-tQQA&amp;sig2=ADa2LhSEXQtSDOSCQ4Oeow&amp;cad=rja">OpenOffice</a> ou <a href="http://www.google.fr/search?q=excel&amp;ie=utf-8&amp;oe=utf-8&amp;aq=t&amp;rls=org.mozilla:fr:official&amp;client=firefox-a#hl=fr&amp;client=firefox-a&amp;hs=Yju&amp;rls=org.mozilla:fr:official&amp;&amp;sa=X&amp;ei=Jw_cTNG8J4GFhQfVmdz-Dw&amp;ved=0CDIQBSgA&amp;q=spreadsheets+online&amp;spell=1&amp;fp=6256e14c32ceb488">quoi que ce soit</a> d’autre. C’est un outil aux capacités extraordinaires. Pas besoin  d’être mathématicien ou statisticien. Tout ce qu’il faut faire c’est  traiter cela comme toute autre information : il faut douter, interroger  et se poser des questions de base.</p>
        <figure>
            <img src="http://api.ning.com/files/Yafo7I8RlO1iIiVOOIuQwueKCC5IfMiJbmQaewlTaxLeg8iUCQ9XrIwjdjUjMIfPdOtOWyJP4kvYiQ6hYAL0E7jctatD7sRa/IED.jpg" />
            <figcaption>Carte géolocalisée et chronologique des bombes artisanales en Afghanistan</figcaption>
        </figure>

        <h2>ADM : Une autre partie du journalisme  de données, c’est ce qu’on appelle la visualisation, la manière de  montrer ces données. Quelle relation vous voyez entre les données et la  visualisation ?</h2>
        <p>Ce qui est intéressant là dedans c’est que par le passé, on avait  tendance à garder les données pour soi. Aujourd’hui, on les publie et  par conséquent, notre rôle est d’aider les gens à les interpréter, à les  analyser, à les montrer. Dans certains cas, un petit tableau suffit ou  même la mise en avant d’un chiffre clé ou la comparaison entre un  chiffre et un autre. Parfois ce simple travail est suffisant mais, dans  d’autres cas, on veut vraiment montrer ces chiffres physiquement. Pour  ce faire, le mariage de la visualisation et des données peut avoir un  impact très fort. Par exemple, dans <a href="http://www.guardian.co.uk/news/datablog/2010/jul/27/wikileaks-afghanistan-data-datajournalism">le cas des fuites de wikileaks</a>, on a <a href="http://www.guardian.co.uk/world/datablog/interactive/2010/jul/26/ied-afghanistan-war-logs">cartographié</a> toutes les bombes artisanales en Afghanistan de manière chronologique. Grâce à  <a href="http://www.scribd.com/doc/34850058">cette visualisation</a>,  on comprend comment leur usage s’est multiplié et pourquoi c’est devenu  un paramètre essentiel de la guerre. Seule la visualisation permet de  montrer cela.</p>
        <p>Maintenant, est-ce qu’il faut être un graphiste pour faire  des visualisations ? Il y a plusieurs approches. Il y a des personnes  qui sont avant tout journalistes et qui réalisent des visualisations  comme <a href="http://www.davidmccandless.com/">David McCandless</a> et son « <a href="http://www.informationisbeautiful.net/">Information Is Beautiful</a> ». Il a une formation de journaliste, il n’est pas graphiste mais il a produit <a href="http://www.amazon.co.uk/exec/obidos/ASIN/0007294662/thegooddrugsg-21">de très belles visualisations</a> qui expliquent bien les choses. En revanche, il arrive qu’on ait  vraiment besoin d’un graphiste pour réaliser une visualisation complexe.</p>
        <p>Il existe, par ailleurs, des outils très simples, accessibles en ligne, qui permettent de réaliser des visuels : <a href="http://www-958.ibm.com/">Manyeyes</a>, <a href="http://timetric.com/">Timetric</a> et même <a href="http://code.google.com/intl/fr/apis/visualization/documentation/gallery.html">Google propose des outils de visualisation</a> que chacun peut utiliser pour raconter une histoire.</p>

        <h2>ADM : Pour clore cet entretien Simon  Rogers, je voudrais évoquer avec vous deux tendances assez fortes  aujourd’hui. La première concerne l’Opendata, on parle aussi d’open  governement, c’est un mouvement qui incite les institutions et les  gouvernements à ouvrir et rendre publiques le plus de données possibles.  Qu’est-ce que vous pensez de cela ? Quelles sont vos attentes ?</h2>
        <p>C’est une évolution très intéressante. Il y a encore un an, on  militait pour accéder aux données et aujourd’hui on croule sous les  données que nous recevons. Par exemple, au Royaume Uni, le Trésor avait  une base de données importante appelée <a href="http://data.gov.uk/dataset/coins">COINS</a> qui répertorie tout ce qui est dépensé par le gouvernement, dans le  moindre détail, il y a des millions d’informations. Le nouveau  gouvernement a rendu ces données publiques, <a href="http://www.freeourdata.org.uk/">on avait beaucoup milité pour ça</a>.  Il y a un an, on voulait accéder à ces infos, aujourd’hui on les a et  il s’agit maintenant d’aider les gens à s’en servir, à les analyser.  Donc <a href="http://coins.guardian.co.uk/coins-explorer/search">ce qu’on a fait avec la base de données COINS</a>,  on a choisi le meilleur format, le .csv. On a choisi la meilleure  période et les départements les plus faciles à comprendre et on a <a href="http://www.guardian.co.uk/news/datablog/2010/oct/18/government-spending-department-2009-10#zoomed-picture">rendu l’ensemble plus intelligible</a>.</p>
        <p>Pour moi, le rôle des journalistes va, de plus en plus, ressembler à  ça. Rendre les données accessibles et compréhensibles. Au Guardian, on  propose aussi un service qui s’appelle <a href="http://www.guardian.co.uk/world-government-data">World Governments Data</a> Search, recherche de données gouvernementales dans le monde. Si vous tapez <a href="http://www.google.fr/search?q=World+Governments+data+search&amp;ie=utf-8&amp;oe=utf-8&amp;aq=t&amp;rls=org.mozilla:fr:official&amp;client=firefox-a#hl=fr&amp;expIds=17259,18168,26637,27189,27403,27409,27510,27547&amp;xhr=t&amp;q=World+Governments+data+&amp;cp=23&amp;pf=p&amp;sclient=psy&amp;client=firefox-a&amp;hs=HbF&amp;rls=org.mozilla:fr%3Aofficial&amp;source=hp&amp;aq=f&amp;aqi=&amp;aql=&amp;oq=World+Governments+data+&amp;gs_rfai=&amp;pbx=1&amp;fp=6256e14c32ceb488">World Government data dans Google</a>,  on sort en premier. En fait notre service répertorie toutes les  publications de données gouvernementales dans le monde et vous permet  par exemple de <a href="http://www.guardian.co.uk/world-government-data/search?q=crime">faire une recherche sur le mot crime</a>, vous aurez alors des chiffres <a href="http://www.guardian.co.uk/world-government-data/dataset/seattle-crime-stats-by-1990-census-tract-1996-2007">des USA</a>, du <a href="http://www.guardian.co.uk/world-government-data/dataset/british-crime-survey-incidents-of-crime-and-victimisation-rates">Royaume Uni</a>, de Chicago, de Californie, de France euh non d’Espagne pas de France, de <a href="http://www.guardian.co.uk/world-government-data/dataset/proceeds-of-crime-statistics">Nouvelle-Zélande</a> etc…et vous pouvez aussi comparer ces chiffres. L’enjeu maintenant c’est de <a href="https://spreadsheets.google.com/ccc?key=tAJzrYuGxXOGbU_HO2s_PrQ#gid=0">trouver une bonne manière de combiner toutes ces données</a> pour permettre aux gens de les utiliser. Parce que les gens veulent  faire des choses avec ces chiffres, chez eux, à la maison et on veut les  aider pour faire partie de ce mouvement.</p>

        <figure>
            <img src="http://owni.fr/files/2010/11/640x413xPublic-spending-graphic-005.jpg.pagespeed.ic.JM7fgyWUph.jpg" />
            <figcaption>Dépenses gouvernementales du Royaume Uni par département 2009-2010</figcaption>
        </figure>

        <h2>ADM : Et comment vous pourriez  convaincre des États de rendre leurs données publiques ou des  populations à inciter leurs États à le faire ? Qu’est-ce que ça apporte à  des sociétés ?</h2>
        <p>Ce qu’il faut comprendre c’est que les gouvernants n’ont rien à  perdre. Aux USA, au Royaume Uni, en Australie ou en Nouvelle-Zélande, le  monde ne s’est pas écroulé parce que les données gouvernementales ont  été rendues publiques ! Cela a tout simplement rendu les choses plus  ouvertes et plus transparentes à une époque où on ne fait plus confiance  aux politiciens, on ne fait plus confiance à la politique. Vous voulez  qu’on vous fasse confiance ? Il faut être ouvert. Rendre ses données  publiques c’est essentiel pour cela, il faut le faire dans un format  pratique pour encourager les gens à s’investir.</p>
        <p>Quand <a href="http://data.gov.uk/">Data.gov.uk</a> a été mis en ligne, ils ont impliqués plein de développeurs pour  permettre aux gens d’accéder à cette masse d’infos, pour moi c’est le  rôle du gouvernement de faire ça. Il y a beaucoup d’exemples aujourd’hui  que <a href="http://www.freeourdata.org.uk/links.php">ceux qui militent pour l’ouverture des données</a> peuvent utiliser pour montrer que les pays ne se sont pas effondrés à  cause de l’open data. L’open data ne peut que renforcer la foi des  peuples dans leurs gouvernants.</p>

        <figure>
            <img src="http://owni.fr/files/2010/11/640x464xCSR640.jpg.pagespeed.ic.nvE6Z3FFaE.jpg" />
        </figure>

        <h2>ADM: Pour finir, je voudrais parler avec vous de <a href="http://wikileaks.org/">Wikileaks</a>,  ce site qui se sert de lanceurs d’alertes, de personnes qui divulguent  des informations secrètes dans le monde et qui les diffuse. Vous avez  été impliqués dans ce qu’on appelle les War logs en Afghanistan (et en  Irak), qu’est ce que vous pensez de cela ?</h2>
        <p>C’est une nouvelle tendance du journalisme. Les journalistes vont  devoir de plus en plus gérer des masses de données et trouver des infos  et des histoires dedans. A l’avenir, un journaliste ne pourra plus dire «  je ne m’occupe pas de tableurs… », cela fera vraiment partie de son  boulot. Au Guardian, cela a vraiment changé notre manière de travailler.  Aujourd’hui les données sont une partie intégrante de notre job.  Maintenant, je pense que les infos de Wikileaks sont excellentes pour  comprendre ce qui se passe. Si vous regardez les rapports divulgués sur  l’Afghanistan, ils montrent à quel point cette guerre est difficile.  Cela raconte notamment comment des gens tentent d’apporter de l’aide  humanitaire dans un village et cela n’intéresse personne, parce que les  villageois ont peur de la corruption etc…Il y a ce genre d’infos où on  voit que les militaires se sentent responsables du bien être des  populations locales. On finit en fait par se demander pourquoi l’armée  ne publie pas ces rapports.</p>
        <p>Il n’y a rien de sensationnel, ça ne change  même pas la manière dont on perçoit cette guerre. Cela fait en tous cas  de la guerre en Afghanistan <a href="http://www.guardian.co.uk/world/datablog/2010/jul/25/wikileaks-afghanistan-data">une des plus documentées de l’histoire,</a> grâce à ces fuites. Est-ce que cela a nuit aux États-Unis ? Pas vraiment je pense. Le gouvernement américain nous a aidé à <a href="http://www.guardian.co.uk/world/2010/aug/10/afghanistan-war-logs-wikileaks-human-rights-groups">retirer les noms cités</a> dans les rapports pour ne pas mettre les personnes en danger.</p>

        <h2>ADM : Et sur le futur du secret, des choses secrètes, est-ce que cela pose une vraie question pour vous ?</h2>
        <p>Cela va être intéressant de voir comment les autorités gèrent cela.  Il y a eu des menaces mais rien de très concret. Et puis il va y avoir  bientôt de nouvelles lois de transparence et de <a href="http://fr.readwriteweb.com/2010/06/18/a-la-une/lislande-vote-une-rsolution-destines-faire-du-pays-refuge-presse-libre/">protection du journalisme en Islande</a>.  Cela va devenir un abri pour les journalistes. Sur le même modèle que  les paradis fiscaux, on aura des paradis journalistiques, des lieux  protégés pour la liberté sur internet. Les gens iront là-bas pour  publier des données sensibles.<br/>
        En tous cas, Wikileaks a  complètement changé le rapport que l’on a avec les documents que l’on  produit, géographiquement notamment. Je pense en tous cas qu’à l’avenir  ce type de fuites ne va faire que se multiplier.</p>
    </div>
    <footer>
        <nav class="internal">
            <a class="previous" href="lopen-data-une-idee-de-gauche.php">L'OpenData : une idée de gauche ?</a>
            <a class="next" href="la-loppsi-contre-lopen-data.php">La LOPPSI contre l'OpenData ?</a>
        </nav>
    </footer>

</article>

<?php require_once('footer.php'); ?>