<?php require_once('header.php'); ?>

<article>
    <header>
        <h1>L'effet pervers de l'OpenData payant</h1>
    </header>
    <div class="body">
        <p>On est encore loin, en France, d'une véritable politique d'ouverture des données publiques. Les décideurs préfèrent blâmer Google et proposer des mécanismes qui musèlent l'innovation.</p>
        <p>La semaine dernière je suis allé à la “conférence débat” “Les actifs immatériels publics, leviers de création de richesse et de modernisation de l’Etat” de l’APIE (Agence du Patrimoine Immatériel de l’État). J’avoue que j’étais assez excité à l’idée d’aller voir de plus près ce qui se trame en matière d’Open Data en France. Je n’en ai été que plus déçu à la fois par la totale absence du débat annoncé, et par le peu de vision claire ou prometteuse fournie.</p>
        <p>Il est difficile de tirer les grandes lignes de ce qui a été présenté dans la première partie, étant celle qui m’intéresse ici (la seconde étant sur les marques, principalement une publicité pour l’INPI, où l’on appris que les Français étaient champions du monde du nombre d’enregistrements de marque par tête, et que c’est là un indicateur fort du bon état de notre économie). La présentation n’était pas tant un débat qu’une accumulation de personnes parlant de leur propre petit bout de sujet, et ces îlots mêmes n’étaient abordés que très superficiellement.</p>
        <p>Le choix des participants était d’entrée de jeu étrange: que faisait l’AFP — qui est indépendante et ne produit pas de données gouvernementales — autour de cette table alors que n’y étaient pas par exemple l’INSEE ou l’IGN ? Il semblerait que leur rôle étaient principalement d’abonder dans le sens de l’APIE en disant le plus de mal possible de la gratuité sur Internet.</p>
        <p>Que l’AFP ne désire pas fournir ses contenus gratuitement, c’est là une chose parfaitement normale, voire louable. Elle est en effet sensée obéir à des impératifs commerciaux afin de s’assurer un maximum d’indépendance. En outre, les problèmes de la presse par rapport à la gratuité sont bien connus, même si irrésolus, mais n’ont aucun rapport direct avec ceux de la gratuité des données gouvernementales.</p>

        <h2>L’obsession Google</h2>
        <p>La première chose qui se dégage cependant des positions des divers intervenants est une incroyable obsession vis à vis de Google. On croirait, à les entendre, que si ce n’était pour Google, la France ferait deux points de PIB annuel en plus, que les réunions de rédaction se feraient au champagne, et que d’un seul homme, d’une seule femme, l’économie française dans son intégralité, du textile aux visagistes et de la métallurgie aux boulangers, se réveillerait d’un pied radicalement innovant.</p>
        <p>Je ne puis retranscrire ici le point auquel cette obsession m’a semblé manifeste — “Google” aurait été un mode de ponctuation oral de la langue française qu’il n’eût pas été cité plus souvent. Sur place, j’ai eu l’impression d’assister à un déraillement ferroviaire au ralenti. Je pensais à la campagne pour Paris de Françoise de Panafieu qui n’a parlé que de Bertrand Delanoë, ou à cette partie de la gauche qui ces dernières années ne discute de rien d’autre que de Sarkozy.</p>
        <p>L’obsession est une stratégie de défaite. Je me fous, cher lecteur, du pays dont vient le plus gros ceci ou cela de telle ou telle industrie. Peu me chaut que certains membres de l’administration s’entichent d’une psychose inutile. Mais j’aimerais bien que là où j’habite, travaille, et entreprends on évite d’inhiber de par trop l’innovation au nom d’illusions protectionnistes. J’aimerais, surtout, pouvoir participer au renouvellement d’une confiance citoyenne en l’État — laquelle passe désormais par une réelle transparence de son fonctionnement.</p>

        <h2>L’Open Data payant: “un open bar où l’on paie ses coups à boire”</h2>
        <p>Et c’est là que le bât me blesse. Car le résultat de cette obsession sur Google est que l’APIE semble déterminée à faire payer pour les données gouvernementales. Oui, de l’Open Data payant. C’est un peu comme un open bar où l’on paie ses coups à boire. Non. C’est comme un open bar où l’on amène ses propres bières pour ensuite devoir les payer.</p>
        <p>Quelle est la logique supputée de cette approche? Eh bien, comme Google n’est pas imposé en France sur la plupart de ses revenus, il faut lui faire payer pour accéder à nos données parce qu’ils pourraient les exploiter et gagner de l’argent avec.Si les facteurs en jeu se limitaient à ceux énoncés au paragraphe précédent, ça pourrait presque faire sens. Mais ça n’est pas le cas.</p>
        <p>Lors de la conférence, tout le monde se targuait de ne surtout pas vouloir créer de barrière à l’entrée pour l’exploitation de ces données, en dépit de leur caractère payant. Une idée suggérée était de les rendre gratuites aux JEI (Jeunes Entreprises Innovantes) pendant deux ans, les faisant payer par la suite en fonction de leur chiffre. Ce genre de proposition a toujours l’air rassurant — ça tient en une phrase, ça semble énoncer une solution, ça cause jeunesse et innovation. Mais il suffit de détailler l’approche au-delà de l’idée en l’air pour y voir toutes les barrières. Premièrement, il faut être une entreprise. Ça élimine déjà tous les bricoleurs citoyens. Ensuite, il faut être une JEI. Ça élimine (à ma connaissance) tous les indépendants et les auto-entrepreneurs, toutes les PMEs de plus de huit ans qui pourraient vouloir s’intéresser à un nouveau domaine sans pour autant avoir beaucoup de ressources de R&D. Ça demande de passer le temps qu’il faut à obtenir le label, temps qui est une barrière en elle-même dans toute PME dont les capacités administratives sont limitées. Finalement, ça pose une barrière à des sociétés étrangères qui pourraient faire bénéficier les citoyens français de diverses innovations en matière de transparence gouvernementale.</p>
        <p>En bref, autant que je puisse le concevoir il est impossible de faire de l’Open Data payant sans créer une entrave à la participation.</p>
        <p>Ceci étant, si ces barrières sont effectivement un problème pour les acteurs les plus petits, elles ne sont qu’un détail pour les plus gros. Remplir divers formulaires administratifs? On a du personnel pour ça. Payer? On a des sous pour ça. Suivant ce raisonnement, une seule conclusion s’impose: non seulement toute forme de contrôle d’accès administratif aux données gouvernementale présente une barrière pour les petits entrants, mais elle ne présente aucun problème aux gros existants.</p>
        <p>Une politique d’Open Data payant non seulement musèle l’innovation locale, mais favorise donc directement la Némésis de l’APIE: Google. Son effet est exactement l’inverse de celui escompté.</p>
        <p>Il faut donc mettre un terme à ces absurdités. Un véritable effort Open Data français permettrait le développement de projets locaux, avantagés précisément du fait de leur localité, et se rémunèrerait tout simplement sur l’impôt prélevé sur une plus grande valeur produite. Je ne parle même pas des avantages citoyens qui découlent de ce type de projet, tant ils semblent avoir échappé à nos amis de l’APIE.</p>
    </div>
    <footer>
        <nav class="internal">
            <a class="previous" href="liberons-les-donnees-de-quelques-aspects-juridiques.php">Libérons les données de quelques aspects juridiques</a>
            <a class="next" href="la-datavolution-est-elle-possible.php">La datavolution est-elle possible ?</a>
        </nav>
    </footer>

</article>

<?php require_once('footer.php'); ?>