<?php require_once('header.php') ?>

<article>
    <header>
        <h1>OpenData : de la marge à la norme</h1>
    </header>
    <div class="body">
        <p>En politique, la mode était à la transparence et à l’ouverture à la fin des années 2000. Nous devons maintenant faire en sorte que l’ouverture des données devienne la norme plutôt qu’une passade.</p>
        <p>En politique, la mode était à la transparence et à l’ouverture à la fin des années 2000. Chaque candidat, dans une bonne partie des pays, a brandit les idéaux de responsabilisation et d’évaluation dans son programme.</p>
        <p>Mais la mode change, en politique comme ailleurs, et nous devons maintenant faire en sorte que l’ouverture des données devienne la norme plutôt qu’une passade. Les intervenants du Personal Democracy Forum de Barcelone ont évoqué quelques pistes en ce sens.</p>

        <h2>Rentrer dans les têtes</h2>

        <p>John Wonderlich, directeur à la Sunlight Foundation, a mené le combat pour l’opendata aux Etats-Unis avec le succès que l’on sait, puisque l’administration Obama a mis en place – et alimente – le site data.gov. Depuis 2006, il met les administrations locales et fédérales sous pression pour qu’elles libèrent leurs données. Pourtant, aujourd’hui, il fait face à un ‘reality check’. C’est le moment où l’on va voir si l’ouverture des données à pénétré les mentalités.</p>
        <p>Il explique comment, en préparation des élections de mi-mandat cette année, ses alliés de 2006 trainent des pieds pour libérer leurs données, maintenant qu’ils sont devenus des candidats sortants. Ils prennent peur et inventent des excuses pour ne pas que l’on puisse juger leur action à l’aune des données publiques.</p>
        <p>La semaine dernière par exemple, un comité du Congrès lui a dit qu’ils ne pouvaient pas stocker de données sur plus de trois ans, alors qu’il ne s’agit que de quelques giga octets en plus. Soit un investissement d’une centaine de dollars, pour une institution disposant d’un budget de plusieurs milliards !</p>
        <p>Cette mauvaise foi, qui ne surprendra pas un Européen, parait déplacée aux Etats-Unis. Là bas, toujours selon John, le principal problème auquel le mouvement opendata a du faire face a été de convaincre les politiciens de s’engager pour publier des documents en sachant qu’ils n’auront pas de couverture médiatique. Ca parait bien peu quand on sait qu’en Europe, le conseiller de la commissaire chargée de la société numérique ne connait même pas les textes régissant l’ouverture des données dans sa propre organisation!</p>

        <h2>Mettre les journalistes de notre côté</h2>

        <p>Si les politiciens sont et resteront une cause perdue, le mouvement opendata doit trouver d’autres relais au sein de la société civile pour diffuser leur message et lui faire prendre racine. Une partie des ressources de la Sunlight Foundation sont ainsi dirigées vers une équipe de journalistes d’investigation chargés d’extraire les informations les plus intéressantes des documents publics.</p>
        <p>Surtout, la Sunlight Foundation offre des formations à l’utilisation de données pour journalistes. Selon John, après ce cours, les journalistes rentrent chez eux et envoient plein de requêtes à leurs administrations locales pour obtenir des informations publiques, l’équivalent chez nous de requêtes CADA.</p>
        <p>L’importance des journalistes a été également évoquée par Marko Rakar, un Croate conseiller politique le jour et blogueur politique la nuit. Il raconte son combat pour obtenir le budget de l’Etat, « le plus important document d’un pays, » selon lui. Le gouvernement croate s’est toujours refusé à communiquer les chiffres au format tableur. En effet, le gouvernement doit fournir au Parlement croate une et unique version de la proposition de budget. Le document officiel est imprimé avant d’être transmis. Pour Zagreb, seul ce document de référence – imprimé – peut être transmis aux journalistes, tous les autres n’étant que des versions de travail susceptibles de contenir des erreurs. Libre ensuite à qui veut de parcourir les 14 000 lignes budgétaires sur papier.</p>
        <p>Marko ne s’est pas laissé démonter et s’est “procuré” une version Excel du budget. Son analyse a révélé plusieurs histoires juteuses, concernant notamment le parc automobile présidentiel et les salaires des fonctionnaires. Les médias se sont alors emparés de l’affaire, qui a, selon lui, été reprise par plus de 40 titres, y compris le journal télévisé du soir.</p>

        <h2>Convaincre la population</h2>

        <p>Le 4e pouvoir reste le soutien le plus évident de l’opendata, les données publiques contenant de nombreux sujets d’articles. Mais on sait bien que la presse périclite et que les journalistes n’ont pas tous les compétences nécessaires à l’analyse de données, quand ils ne sont pas tout simplement de mèche avec les administrations locales.</p>
        <p>Pour pérenniser le mouvement de l’opendata, il faut que chaque citoyen considère comme normal le droit d’accès aux documents administratifs. Que chaque fonctionnaire trouve normal qu’on puisse lui demander le montant de son salaire. Que les ministres ne soient pas offusqués lorsqu’on publie le prix de leur hôtel.</p>
        <p>Sur ce dernier point, suite à un sondage exclusif et très peu scientifique, je suis en mesure d’affirmer que les Européens ne sont pas en retard. Alec Ross, conseiller d’Hillary Clinton, a jugé “normal” que les contribuables américains connaissent le montant de ses notes de frais, mais n’en a pas dit plus. Constantijn van Oranje-Nassau, de la Commission Européenne, a, lui, admis ne pas connaitre le prix de sa chambre au Novotel, mais a affirmer payer les taxis de sa poche.</p>
        <p>Au-delà des ministres, force est de constater que les citoyens Européens ne connaissent que très peu la législation sur l’ouverture des données. Helen Darbishire, directrice de l’ONG Access Info, raconte qu’elle avait monté un stand, carrefour de l’Odéon à Paris, et distribué des flyers aux passants sur la loi du 17 juillet 1978. Pas un ne connaissait le texte !</p>
        <p>L’apathie des citoyens et des contribuables reste le problème numéro un. Sans soutien populaire, les avancées effectuées sur l’opendata ne se concrétiseront jamais. Alvaro Ortiz, l’un des pionniers du mouvement en Espagne, le dit sans détour. Le sujet était attirant avant la crise, explique-t-il, mais la montée du chômage l’a relégué en bas de la liste des promesses politiques.</p>
        <p>Dejan Milovac, qui dirige une ONG luttant contre la corruption au Monténégro, explique comment il a trouvé un soutien populaire pour combattre un projet de construction illégale sur le littoral. Un consortium russe a commencé à construire un projet de 200m€, sans bien sûr attendre l’approbation du permis de construire – le parrain local couvrait l’affaire.</p>
        <p>Il a montré quels étaient les réseaux de pouvoir à l’œuvre dans l’affaire, et comment l’argent public était détourné ou les taxes impayées. Pour lui, il est fondamental de faire comprendre aux citoyens qu’il existe bien une différence entre 1m€ et 3m€, par exemple, en expliquant ce qui peut être fait avec l’argent manquant. La mobilisation a été telle que Dejan a obtenu que les permis de construire soient désormais disponibles en ligne, afin que chacun puisse vérifier la légalité des projets de construction.</p>
    </div>
</article>

<?php require_once('footer.php') ?>